# Generated by Django 4.1 on 2022-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=256, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "open"), ("close", "close")],
                        default="OPEN",
                        max_length=5,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        default="LOW",
                        max_length=6,
                    ),
                ),
                ("createdAt", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
